### ISSUE TITLE
Home Assistant 0.103.5 Issues?

### ISSUE THREAD

**Issue by DaveO16176** [mikelawrence/homeassistant-custom-components#4]
Does anyone know if HA 0.103.5 broke the SenseMe component?  I just upgraded my server this morning and suddenly the component stopped working.  I'm getting a configuration invalid when I have HA check my configuration files.  I get a "Component error: senseme - Requirements for senseme not found: ['SenseMe==0.1.5']."

I was wondering if it had something to do with the HA team moving where they import Python packages as of version 103?

**Comment by mikelawrence** [comment]
I've been running Home Assistant 0.103.5 since it became available and the SenseMe component is working fine. The ['SenseMe==0.1.5'] [library](https://pypi.org/project/SenseMe/) is automatically loaded by Home Assistant. Maybe you have a file system issue or Home Assistant could not access the library on the internet.

**Comment by DaveO16176** [comment]
It was a firewall issue that blocked access to PyPI.  Thanks for the help.
